// <auto-generated />
using System;
using CodecoolMaterialAPI.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodecoolMaterialAPI.Migrations
{
    [DbContext(typeof(CodecoolMaterialDbContext))]
    partial class CodecoolMaterialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodecoolMaterialAPI.DAL.Models.Author", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Author");
                });

            modelBuilder.Entity("CodecoolMaterialAPI.DAL.Models.EduMaterialNavPoint", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EduMaterialTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("EduMaterialTypeID");

                    b.ToTable("EduMaterialNavPoint");
                });

            modelBuilder.Entity("CodecoolMaterialAPI.DAL.Models.EduMaterialType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EduMaterialType");
                });

            modelBuilder.Entity("CodecoolMaterialAPI.DAL.Models.Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EduMaterialNavPointID")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EduMaterialNavPointID");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("CodecoolMaterialAPI.DAL.Models.EduMaterialNavPoint", b =>
                {
                    b.HasOne("CodecoolMaterialAPI.DAL.Models.Author", "Author")
                        .WithMany("EduMaterialNavPoints")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodecoolMaterialAPI.DAL.Models.EduMaterialType", "EduMaterialType")
                        .WithMany("EduMaterialNavPoints")
                        .HasForeignKey("EduMaterialTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("EduMaterialType");
                });

            modelBuilder.Entity("CodecoolMaterialAPI.DAL.Models.Review", b =>
                {
                    b.HasOne("CodecoolMaterialAPI.DAL.Models.EduMaterialNavPoint", "EduMaterialNavPoint")
                        .WithMany("Reviews")
                        .HasForeignKey("EduMaterialNavPointID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EduMaterialNavPoint");
                });

            modelBuilder.Entity("CodecoolMaterialAPI.DAL.Models.Author", b =>
                {
                    b.Navigation("EduMaterialNavPoints");
                });

            modelBuilder.Entity("CodecoolMaterialAPI.DAL.Models.EduMaterialNavPoint", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CodecoolMaterialAPI.DAL.Models.EduMaterialType", b =>
                {
                    b.Navigation("EduMaterialNavPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
